# Generated by Django 6.0.3 on 2026-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
